import LandingNavbar from "./LandingNavbar";

function LandingPage({ onGetStarted, onToggleDark }) {
  const circumference = 2 * Math.PI * 28;
  const progressPercent = (4 / 90) * 100;
  const strokeDashoffset = circumference - (progressPercent / 100) * circumference;

  return (
    <div className="antialiased selection:bg-primary selection:text-white">
      <LandingNavbar onGetStarted={onGetStarted} onToggleDark={onToggleDark} />

      <div className="pt-32 pb-20 lg:pt-40 lg:pb-28 overflow-hidden relative">
        <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-primary/10 rounded-full blur-3xl dark:bg-primary/5" />
        <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-80 h-80 bg-blue-500/10 rounded-full blur-3xl dark:bg-blue-500/5" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center">
            <div className="text-center lg:text-left">
              <div className="inline-flex items-center space-x-2 bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-full px-4 py-1.5 mb-6 shadow-sm">
                <span className="material-icons-round text-primary text-sm">auto_awesome</span>
                <span className="text-xs font-semibold uppercase tracking-wide text-muted-light dark:text-muted-dark">
                  Generated by Amara AI Agent
                </span>
              </div>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight leading-tight text-gray-900 dark:text-white mb-6">
                Metabolic Reset <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-emerald-400">
                  + Energy Optimization
                </span>
              </h1>
              <p className="text-lg sm:text-xl text-muted-light dark:text-muted-dark mb-8 max-w-2xl mx-auto lg:mx-0 leading-relaxed">
                Building a lifestyle with AI-driven health protocols. Your personalized 90-day journey to shift baseline
                energy utilization, optimize for longevity, and target mitochondrial density.
              </p>
              <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-4">
                <button
                  type="button"
                  className="w-full sm:w-auto bg-primary text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-opacity-90 transition-all shadow-xl shadow-primary/25 flex items-center justify-center space-x-2"
                  onClick={onGetStarted}
                >
                  <span>Start Your 90-Day Protocol</span>
                  <span className="material-icons-round">arrow_forward</span>
                </button>
                <span className="text-sm text-muted-light dark:text-muted-dark">Includes 7-day free trial</span>
              </div>
              <div className="mt-10 flex items-center justify-center lg:justify-start space-x-6 text-sm font-medium text-muted-light dark:text-muted-dark">
                <div className="flex items-center">
                  <span className="material-icons-round text-primary mr-2 text-base">check_circle</span>
                  Clinical Expert Team
                </div>
                <div className="flex items-center">
                  <span className="material-icons-round text-primary mr-2 text-base">check_circle</span>
                  Version 2.1 AI Model
                </div>
              </div>
            </div>

            <div className="relative mx-auto w-full max-w-[400px] lg:max-w-md">
              <div className="bg-card-light dark:bg-card-dark rounded-[2rem] p-6 pb-20 shadow-2xl border border-gray-100 dark:border-gray-800 relative z-10">
                <div className="flex justify-between items-center mb-6">
                  <div>
                    <p className="text-xs font-bold text-muted-light dark:text-muted-dark uppercase tracking-wider mb-1">
                      Current Progress
                    </p>
                    <div className="flex items-baseline space-x-1">
                      <h3 className="text-3xl font-bold text-gray-900 dark:text-white">Day 4</h3>
                      <span className="text-muted-light dark:text-muted-dark">/ 90</span>
                    </div>
                    <p className="text-primary font-medium text-sm mt-1">On Track</p>
                  </div>
                  <div className="relative w-16 h-16 flex items-center justify-center">
                    <svg className="w-full h-full transform -rotate-90" viewBox="0 0 64 64">
                      <circle
                        className="text-gray-100 dark:text-gray-800"
                        cx="32"
                        cy="32"
                        fill="transparent"
                        r="28"
                        stroke="currentColor"
                        strokeWidth="6"
                      />
                      <circle
                        className="text-primary"
                        cx="32"
                        cy="32"
                        fill="transparent"
                        r="28"
                        stroke="currentColor"
                        strokeDasharray={circumference}
                        strokeDashoffset={strokeDashoffset}
                        strokeLinecap="round"
                        strokeWidth="6"
                      />
                    </svg>
                    <span className="material-icons-round text-primary absolute text-2xl">bolt</span>
                  </div>
                </div>
                <div className="gradient-card rounded-2xl p-6 text-white mb-6 relative overflow-hidden group">
                  <div
                    className="absolute inset-0 opacity-20"
                    style={{
                      backgroundImage:
                        "url(\"data:image/svg+xml,%3Csvg width='20' height='20' viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='%23ffffff' fill-opacity='1' fill-rule='evenodd'%3E%3Ccircle cx='3' cy='3' r='3'/%3E%3Ccircle cx='13' cy='13' r='3'/%3E%3C/g%3E%3C/svg%3E\")",
                    }}
                  />
                  <div className="relative z-10">
                    <div className="flex items-center space-x-2 mb-3">
                      <span className="material-icons-round text-primary text-sm">auto_awesome</span>
                      <span className="text-xs font-bold tracking-widest uppercase text-gray-300">Protocol Focus</span>
                    </div>
                    <h4 className="text-lg font-semibold mb-2 text-primary">Target: Metabolic Flexibility</h4>
                    <p className="text-sm text-gray-300 leading-relaxed mb-4">
                      This protocol shifts your baseline energy utilization to optimize for longevity and performance.
                    </p>
                    <div className="flex flex-wrap gap-2">
                      <span className="px-3 py-1 bg-white/10 rounded-full text-xs font-medium border border-white/10">
                        VO2 Max Focus
                      </span>
                      <span className="px-3 py-1 bg-white/10 rounded-full text-xs font-medium border border-white/10">
                        Deep Sleep
                      </span>
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-gray-50 dark:bg-gray-800/50 p-4 rounded-xl border border-gray-100 dark:border-gray-800">
                    <div className="w-8 h-8 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center mb-3">
                      <span className="material-icons-round text-primary text-sm">favorite</span>
                    </div>
                    <p className="text-xs text-muted-light dark:text-muted-dark font-medium uppercase mb-1">
                      Cardiovascular
                    </p>
                    <p className="text-lg font-bold text-gray-900 dark:text-white">Excellent</p>
                    <p className="text-xs text-primary mt-1 font-medium">↗ +4.2%</p>
                  </div>
                  <div className="bg-gray-50 dark:bg-gray-800/50 p-4 rounded-xl border border-gray-100 dark:border-gray-800">
                    <div className="w-8 h-8 rounded-full bg-orange-100 dark:bg-orange-900/30 flex items-center justify-center mb-3">
                      <span className="material-icons-round text-orange-500 text-sm">bedtime</span>
                    </div>
                    <p className="text-xs text-muted-light dark:text-muted-dark font-medium uppercase mb-1">
                      Recovery
                    </p>
                    <p className="text-lg font-bold text-gray-900 dark:text-white">Improving</p>
                    <p className="text-xs text-orange-500 mt-1 font-medium">→ Stable</p>
                  </div>
                </div>
                <div className="absolute bottom-6 left-1/2 transform -translate-x-1/2 w-[90%]">
                  <button
                    type="button"
                    className="w-full bg-primary hover:bg-emerald-600 text-white font-semibold py-3 px-4 rounded-xl shadow-lg transition-colors flex items-center justify-center space-x-2"
                    onClick={onGetStarted}
                  >
                    <span>View This Week&apos;s Plan</span>
                    <span className="material-icons-round text-sm">arrow_forward</span>
                  </button>
                </div>
              </div>
              <div className="absolute -z-10 top-10 -right-10 w-full h-full bg-gray-200 dark:bg-gray-800 rounded-[2rem] transform rotate-6 opacity-40" />
            </div>
          </div>
        </div>
      </div>

      <section id="how-it-works" className="py-20 bg-white dark:bg-gray-900 border-t border-gray-100 dark:border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">Your 90-Day Journey</h2>
            <p className="text-muted-light dark:text-muted-dark">
              A scientifically structured protocol designed to adapt to your body&apos;s response in real-time.
            </p>
          </div>
          <div className="relative">
            <div className="hidden md:block absolute top-1/2 left-0 w-full h-1 bg-gray-100 dark:bg-gray-800 -translate-y-1/2 z-0" />
            <div className="grid md:grid-cols-3 gap-12 relative z-10">
              <div className="group">
                <div className="bg-card-light dark:bg-card-dark p-8 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-xl hover:border-primary/30 transition-all duration-300 relative h-full">
                  <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mb-6 group-hover:bg-primary group-hover:text-white transition-colors text-primary">
                    <span className="material-icons-round text-3xl">play_arrow</span>
                  </div>
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white">Foundation</h3>
                    <span className="bg-primary/10 text-primary text-xs font-bold px-2 py-1 rounded uppercase">
                      Current
                    </span>
                  </div>
                  <p className="text-sm text-primary font-medium mb-4">Days 1–30 • Metabolic Adaptation</p>
                  <p className="text-muted-light dark:text-muted-dark text-sm leading-relaxed">
                    Establishing baseline metrics and introducing gentle stressors to prime your metabolic machinery for
                    change.
                  </p>
                  <div className="w-full bg-gray-100 dark:bg-gray-700 h-1.5 rounded-full mt-6 overflow-hidden">
                    <div className="bg-primary h-full w-1/4 rounded-full" />
                  </div>
                </div>
              </div>
              <div className="group">
                <div className="bg-card-light dark:bg-card-dark p-8 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-xl hover:border-primary/30 transition-all duration-300 relative h-full opacity-70 hover:opacity-100">
                  <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center mb-6 text-muted-light dark:text-muted-dark group-hover:text-primary transition-colors">
                    <span className="material-icons-round text-3xl">bolt</span>
                  </div>
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white">Acceleration</h3>
                    <span className="material-icons-round text-muted-light text-sm">lock</span>
                  </div>
                  <p className="text-sm text-muted-light dark:text-muted-dark font-medium mb-4">
                    Days 31–60 • High Intensity
                  </p>
                  <p className="text-muted-light dark:text-muted-dark text-sm leading-relaxed">
                    Increasing protocol intensity to maximize mitochondrial density and force physiological adaptation.
                  </p>
                </div>
              </div>
              <div className="group">
                <div className="bg-card-light dark:bg-card-dark p-8 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-xl hover:border-primary/30 transition-all duration-300 relative h-full opacity-70 hover:opacity-100">
                  <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center mb-6 text-muted-light dark:text-muted-dark group-hover:text-primary transition-colors">
                    <span className="material-icons-round text-3xl">all_inclusive</span>
                  </div>
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white">Optimization</h3>
                    <span className="material-icons-round text-muted-light text-sm">lock</span>
                  </div>
                  <p className="text-sm text-muted-light dark:text-muted-dark font-medium mb-4">
                    Days 61–90 • Integration
                  </p>
                  <p className="text-muted-light dark:text-muted-dark text-sm leading-relaxed">
                    Stabilizing new metabolic baselines and integrating habits for long-term sustainable performance.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="science" className="py-20 bg-background-light dark:bg-background-dark">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div className="order-2 lg:order-1 grid grid-cols-2 gap-6">
              <div className="bg-white dark:bg-card-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800">
                <div className="flex justify-between items-start mb-4">
                  <div className="p-2 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                    <span className="material-icons-round text-blue-500">fitness_center</span>
                  </div>
                  <span className="text-xs font-bold text-green-500 bg-green-50 dark:bg-green-900/20 px-2 py-1 rounded">
                    +12%
                  </span>
                </div>
                <h4 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">Lean Mass</h4>
                <p className="text-sm text-muted-light dark:text-muted-dark">Consistent Growth</p>
              </div>
              <div className="bg-white dark:bg-card-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800">
                <div className="flex justify-between items-start mb-4">
                  <div className="p-2 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
                    <span className="material-icons-round text-purple-500">monitor_heart</span>
                  </div>
                  <span className="text-xs font-bold text-green-500 bg-green-50 dark:bg-green-900/20 px-2 py-1 rounded">
                    -8 bpm
                  </span>
                </div>
                <h4 className="text-2xl font-bold text-gray-900 dark:text-white mb-1">RHR</h4>
                <p className="text-sm text-muted-light dark:text-muted-dark">Resting Heart Rate</p>
              </div>
              <div className="col-span-2 bg-white dark:bg-card-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800">
                <div className="flex items-center justify-between mb-6">
                  <div className="flex items-center space-x-3">
                    <div className="p-2 bg-primary/10 rounded-lg">
                      <span className="material-icons-round text-primary">psychology</span>
                    </div>
                    <div>
                      <h4 className="text-lg font-bold text-gray-900 dark:text-white">Cognitive Clarity</h4>
                      <p className="text-xs text-muted-light dark:text-muted-dark">Self-reported daily score</p>
                    </div>
                  </div>
                  <span className="text-primary font-bold">8.5/10</span>
                </div>
                <div className="h-24 flex items-end justify-between gap-2 px-2">
                  <div className="w-full bg-gray-100 dark:bg-gray-700 rounded-t-sm h-[40%]" />
                  <div className="w-full bg-gray-100 dark:bg-gray-700 rounded-t-sm h-[55%]" />
                  <div className="w-full bg-gray-100 dark:bg-gray-700 rounded-t-sm h-[45%]" />
                  <div className="w-full bg-gray-100 dark:bg-gray-700 rounded-t-sm h-[60%]" />
                  <div className="w-full bg-primary/30 rounded-t-sm h-[75%]" />
                  <div className="w-full bg-primary/60 rounded-t-sm h-[85%]" />
                  <div className="w-full bg-primary rounded-t-sm h-[92%]" />
                </div>
              </div>
            </div>
            <div className="order-1 lg:order-2">
              <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-6">Track What Matters</h2>
              <p className="text-lg text-muted-light dark:text-muted-dark mb-8">
                The protocol isn&apos;t just about weight. We track deep biomarkers, recovery metrics, and cognitive
                function to ensure holistic improvement.
              </p>
              <ul className="space-y-4">
                <li className="flex items-center text-muted-light dark:text-muted-dark">
                  <span className="material-icons-round text-primary mr-3">check_circle</span>
                  Real-time adaptation based on HRV
                </li>
                <li className="flex items-center text-muted-light dark:text-muted-dark">
                  <span className="material-icons-round text-primary mr-3">check_circle</span>
                  Integration with Oura, Whoop, and Apple Health
                </li>
                <li className="flex items-center text-muted-light dark:text-muted-dark">
                  <span className="material-icons-round text-primary mr-3">check_circle</span>
                  Daily check-ins with AI health coach
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <footer className="bg-white dark:bg-card-dark border-t border-gray-100 dark:border-gray-800 pt-16 pb-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row justify-between items-center mb-8">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <span className="material-icons-round text-primary text-2xl">bolt</span>
              <span className="font-bold text-lg tracking-tight text-gray-900 dark:text-white">PROTOCOL</span>
            </div>
            <div className="flex space-x-6 text-sm text-muted-light dark:text-muted-dark">
              <a className="hover:text-primary transition-colors" href="#">
                Privacy
              </a>
              <a className="hover:text-primary transition-colors" href="#">
                Terms
              </a>
              <a className="hover:text-primary transition-colors" href="#">
                Support
              </a>
            </div>
          </div>
          <div className="text-center text-xs text-muted-light dark:text-muted-dark">
            © 2025 Protocol Health AI. All rights reserved. Designed for longevity.
          </div>
        </div>
      </footer>
    </div>
  );
}

export default LandingPage;
