function Step3ProtocolDashboard({ onViewPlan }) {
  // Use Plus Jakarta Sans for dashboard (matches design)
  const userName = "Sarah";
  const progressPercent = (4 / 90) * 100;
  const circumference = 2 * Math.PI * 36;
  const strokeDashoffset = circumference - (progressPercent / 100) * circumference;

  return (
    <div className="font-jakarta">
      <main className="flex-grow max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        <div className="mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-50 dark:bg-green-900/30 text-primary text-xs font-bold uppercase tracking-wider mb-3 border border-green-100 dark:border-green-800">
            <span className="material-icons-round text-sm">auto_awesome</span>
            Generated by Amara AI Agent
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold mb-2">Your 90-Day Metabolic Reset</h1>
          <p className="text-subtext-light dark:text-subtext-dark text-lg">
            Customized for <span className="text-primary font-semibold">{userName}</span> • Version 2.1
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-8 space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-surface-light dark:bg-surface-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800 flex items-center justify-between">
                <div>
                  <p className="text-xs font-bold text-subtext-light dark:text-subtext-dark uppercase tracking-wide mb-1">
                    Current Progress
                  </p>
                  <div className="flex items-baseline gap-1">
                    <span className="text-4xl font-bold text-text-light dark:text-text-dark">Day 4</span>
                    <span className="text-subtext-light dark:text-subtext-dark font-medium">/ 90</span>
                  </div>
                  <p className="text-primary font-medium text-sm mt-1 flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-primary inline-block" />
                    On Track
                  </p>
                </div>
                <div className="relative w-20 h-20 flex items-center justify-center">
                  <svg className="w-full h-full transform -rotate-90" viewBox="0 0 80 80">
                    <circle
                      className="text-gray-100 dark:text-gray-700"
                      cx="40"
                      cy="40"
                      fill="transparent"
                      r="36"
                      stroke="currentColor"
                      strokeWidth="8"
                    />
                    <circle
                      className="text-primary"
                      cx="40"
                      cy="40"
                      fill="transparent"
                      r="36"
                      stroke="currentColor"
                      strokeDasharray={circumference}
                      strokeDashoffset={strokeDashoffset}
                      strokeLinecap="round"
                      strokeWidth="8"
                    />
                  </svg>
                  <span className="material-icons-round text-primary absolute text-2xl">bolt</span>
                </div>
              </div>
              <div className="bg-surface-light dark:bg-surface-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800 flex flex-col justify-center">
                <p className="text-xs font-bold text-subtext-light dark:text-subtext-dark uppercase tracking-wide mb-1">
                  Status
                </p>
                <div className="text-2xl font-bold text-text-light dark:text-text-dark mb-1">Week 1 • Active</div>
                <div className="flex items-center gap-2 mt-2">
                  <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200">
                    Phase 1: Foundation
                  </span>
                </div>
              </div>
            </div>

            <div className="relative overflow-hidden rounded-2xl bg-gray-900 text-white shadow-lg group">
              <div className="absolute inset-0 bg-gradient-to-br from-gray-900 via-gray-800 to-black z-0" />
              <div className="absolute inset-0 opacity-40 z-0">
                <svg height="100%" width="100%" xmlns="http://www.w3.org/2000/svg">
                  <defs>
                    <pattern id="wave" height="20" width="100" patternUnits="userSpaceOnUse" x="0" y="0">
                      <path
                        d="M0 10 Q25 20 50 10 T100 10"
                        fill="none"
                        stroke="rgba(16, 185, 129, 0.2)"
                        strokeWidth="2"
                      />
                    </pattern>
                  </defs>
                  <rect fill="url(#wave)" height="100%" width="100%" />
                </svg>
                <div className="absolute bottom-0 right-0 w-64 h-64 bg-primary blur-3xl opacity-20 rounded-full" />
              </div>
              <div className="relative z-10 p-8">
                <div className="flex items-center gap-2 mb-4 text-primary font-bold tracking-wider text-sm uppercase">
                  <span className="material-icons-round text-base">auto_awesome</span>
                  Protocol Focus
                </div>
                <h2 className="text-2xl md:text-3xl font-bold mb-4 leading-snug">
                  Target: <span className="text-primary">Metabolic Flexibility</span>
                </h2>
                <p className="text-gray-300 text-lg leading-relaxed mb-8 max-w-2xl">
                  This protocol shifts your baseline energy utilization to optimize for longevity and performance,
                  specifically targeting mitochondrial density.
                </p>
                <div className="flex flex-wrap gap-3 mb-8">
                  <span className="px-4 py-2 bg-white/10 backdrop-blur-sm rounded-full text-sm font-medium border border-white/10">
                    VO2 Max Focus
                  </span>
                  <span className="px-4 py-2 bg-white/10 backdrop-blur-sm rounded-full text-sm font-medium border border-white/10">
                    Deep Sleep
                  </span>
                  <span className="px-4 py-2 bg-white/10 backdrop-blur-sm rounded-full text-sm font-medium border border-white/10">
                    Cortisol Mgmt
                  </span>
                </div>
                <button
                  type="button"
                  className="w-full md:w-auto bg-primary hover:bg-primary-dark text-white font-bold py-3 px-6 rounded-xl flex items-center justify-center gap-2 transition-all transform active:scale-95 shadow-lg shadow-primary/30"
                  onClick={onViewPlan}
                >
                  View This Week&apos;s Plan
                  <span className="material-icons-round">arrow_forward</span>
                </button>
              </div>
            </div>

            <div>
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-bold text-text-light dark:text-text-dark">Key Health Areas</h3>
                <a className="text-xs font-bold text-primary hover:text-primary-dark uppercase tracking-wide" href="#">
                  View All
                </a>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-surface-light dark:bg-surface-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800">
                  <div className="w-10 h-10 rounded-full bg-green-50 dark:bg-green-900/30 flex items-center justify-center mb-4 text-primary">
                    <span className="material-icons-round">favorite</span>
                  </div>
                  <p className="text-xs font-bold text-subtext-light dark:text-subtext-dark uppercase mb-1">
                    Cardiovascular
                  </p>
                  <p className="text-2xl font-bold text-text-light dark:text-text-dark mb-2">Excellent</p>
                  <p className="text-sm font-medium text-primary flex items-center gap-1">
                    <span className="material-icons-round text-base">trending_up</span>
                    +4.2%
                  </p>
                </div>
                <div className="bg-surface-light dark:bg-surface-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800">
                  <div className="w-10 h-10 rounded-full bg-orange-50 dark:bg-orange-900/30 flex items-center justify-center mb-4 text-orange-500">
                    <span className="material-icons-round">bedtime</span>
                  </div>
                  <p className="text-xs font-bold text-subtext-light dark:text-subtext-dark uppercase mb-1">
                    Recovery
                  </p>
                  <p className="text-2xl font-bold text-text-light dark:text-text-dark mb-2">Improving</p>
                  <p className="text-sm font-medium text-orange-500 flex items-center gap-1">
                    <span className="material-icons-round text-base">arrow_right_alt</span>
                    Stable
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-4 space-y-6">
            <div className="bg-surface-light dark:bg-surface-dark p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800 h-full">
              <h3 className="text-lg font-bold text-text-light dark:text-text-dark mb-6">Protocol Phases</h3>
              <div className="relative">
                <div className="absolute left-6 top-8 bottom-8 w-0.5 bg-gray-200 dark:bg-gray-700" />
                <div className="space-y-8 relative">
                  <div className="flex gap-4">
                    <div className="relative z-10 flex-shrink-0">
                      <div className="w-12 h-12 rounded-full border-2 border-primary bg-surface-light dark:bg-surface-dark flex items-center justify-center shadow-lg shadow-primary/20">
                        <span className="material-icons-round text-primary text-2xl">play_arrow</span>
                      </div>
                    </div>
                    <div className="pt-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="font-bold text-text-light dark:text-text-dark">Foundation</h4>
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-primary text-white uppercase tracking-wide">
                          Current
                        </span>
                      </div>
                      <p className="text-sm text-subtext-light dark:text-subtext-dark mb-2">
                        Days 1–30 • Metabolic Adaptation
                      </p>
                      <div className="w-full bg-gray-100 dark:bg-gray-700 h-1.5 rounded-full overflow-hidden">
                        <div className="bg-primary h-full w-[15%] rounded-full" />
                      </div>
                    </div>
                  </div>
                  <div className="flex gap-4 opacity-70">
                    <div className="relative z-10 flex-shrink-0">
                      <div className="w-12 h-12 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center text-subtext-light dark:text-subtext-dark">
                        <span className="material-icons-round text-xl">lock</span>
                      </div>
                    </div>
                    <div className="pt-1">
                      <h4 className="font-bold text-text-light dark:text-text-dark mb-1">Acceleration</h4>
                      <p className="text-sm text-subtext-light dark:text-subtext-dark">Days 31–60 • High Intensity</p>
                    </div>
                  </div>
                  <div className="flex gap-4 opacity-70">
                    <div className="relative z-10 flex-shrink-0">
                      <div className="w-12 h-12 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center text-subtext-light dark:text-subtext-dark">
                        <span className="material-icons-round text-xl">lock</span>
                      </div>
                    </div>
                    <div className="pt-1">
                      <h4 className="font-bold text-text-light dark:text-text-dark mb-1">Optimization</h4>
                      <p className="text-sm text-subtext-light dark:text-subtext-dark">Days 61–90 • Integration</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="mt-12 bg-gray-50 dark:bg-gray-800/50 p-4 rounded-xl border border-gray-100 dark:border-gray-700">
                <h5 className="text-sm font-bold text-text-light dark:text-text-dark mb-2 flex items-center gap-2">
                  <span className="material-icons-round text-primary text-sm">tips_and_updates</span>
                  Daily Insight
                </h5>
                <p className="text-xs text-subtext-light dark:text-subtext-dark leading-relaxed">
                  Your HRV is trending up this week. Consider adding an extra 10 minutes of Zone 2 cardio today to
                  capitalize on recovery.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className="bg-surface-light dark:bg-surface-dark border-t border-gray-200 dark:border-gray-800 mt-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
          <div className="bg-gradient-to-r from-gray-900 to-gray-800 dark:from-primary dark:to-primary-dark rounded-2xl p-8 md:p-10 flex flex-col md:flex-row items-center justify-between gap-8 shadow-xl relative overflow-hidden">
            <div className="absolute top-0 right-0 -mt-10 -mr-10 w-40 h-40 bg-white/10 rounded-full blur-3xl" />
            <div className="absolute bottom-0 left-0 -mb-10 -ml-10 w-40 h-40 bg-white/10 rounded-full blur-3xl" />
            <div className="relative z-10 max-w-xl text-center md:text-left">
              <h2 className="text-2xl md:text-3xl font-bold text-white mb-3">Get the Full Experience</h2>
              <p className="text-gray-300 dark:text-white/90 text-lg">
                Track your daily meals, sync wearables, and chat with your AI coach anytime on our mobile app.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row items-center gap-6 relative z-10">
              <div className="bg-white p-2 rounded-lg shadow-lg hidden lg:block">
                <div className="w-24 h-24 bg-gray-100 flex items-center justify-center rounded border border-gray-200">
                  <span className="material-icons-round text-4xl text-gray-400">qr_code_2</span>
                </div>
                <p className="text-[10px] text-center mt-1 font-medium text-gray-500">Scan to download</p>
              </div>
              <div className="flex flex-col gap-3 w-full sm:w-auto">
                <button
                  type="button"
                  className="bg-black text-white px-5 py-2.5 rounded-lg flex items-center gap-3 hover:bg-gray-900 transition-colors border border-gray-700 w-full sm:w-44"
                >
                  <span className="material-icons-round text-2xl">apple</span>
                  <div className="text-left">
                    <div className="text-[10px] uppercase font-medium text-gray-400">Download on the</div>
                    <div className="text-sm font-bold leading-none">App Store</div>
                  </div>
                </button>
                <button
                  type="button"
                  className="bg-black text-white px-5 py-2.5 rounded-lg flex items-center gap-3 hover:bg-gray-900 transition-colors border border-gray-700 w-full sm:w-44"
                >
                  <span className="material-icons-round text-2xl">android</span>
                  <div className="text-left">
                    <div className="text-[10px] uppercase font-medium text-gray-400">Get it on</div>
                    <div className="text-sm font-bold leading-none">Google Play</div>
                  </div>
                </button>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default Step3ProtocolDashboard;
